### ISSUE TITLE
False exceptions "Inputs must be real integers." in integer_manipulations.py ?

### ISSUE THREAD

**Issue by eschmidt42** [adehgha/GBpy#1]
Hi,

I've been trying to do the tutorial #2 from your website and encountered a small bug. Running the given code of tutorial #2 I encountered the exception "Inputs must be real integers." caused by integer_manipulations's gcd_array and lcm_array. Checking the inputs manually I found they were actually of integer type but not the excpected 'int64'.

If I'm correct and it doesn't matter what integer type is handed over i.e. int32 instead of 'int64' I suggest a slight modification for the conditional statements in lines 48 and 146 to use something like:

`if not issubclass(input.dtype.type,np.integer):`

instead of

`if input.dtype.name != 'int64:`

Best regards,
Eric

**Comment by adehgha** [comment]
Hi Eric,

To reach a reasonable numerical stability in converting a real number to its closest rational number, we need to work with long integers (i.e. `int64`) particularly in `gcd_array` and `lcm_array` . That is the reason why we are forcing the user to specifically use the `int64` for integers.

But I am curious to know in what part of the Tutorial#2 you are encountering this issue.
I would appreciate it if you could specify the section of the tutorial in which you encountered this issue (please mention the section# e.g. _2.3. Extracting the Misorientation Operator_). I could not reproduce this issue on my machine by solely following the Tutorial#2 steps.

Many thanks,

Arash

**Comment by eschmidt42** [comment]
Hi Arash,

Thank you for your quick response. Sorry that I didn't specify the
location more clearly. I got the exception when calling the function
gb_2d_csl of GBpy.bp_basis when trying to find the planar basis set in
the first cell under 3.3 in tutorial #2. I've attached the traceback as
a pdf as well as the notebook I created based on your tutorial (please
forgive the not present color coding). Also, I'm using python2.7 on an
up-to-date anaconda with jupyter notebook on windows 8.

I see the point of using int64. So would it be a better solution to, for
example, directly set the array type 'input' variable in 'lcm_array' to
int64 (i.e. input = np.array(input,dtype='int64'))? Both the manual
specification of the array as above and the issubclass statement give
the same answers as expected from the tutorial.

I've probably just overlooked it. But I was wondering how you would
recommend to set up atomistic models for simulation, i.e. for a given
number of CSL unit cells along each of the CSL plane vectors?

Thank you!

Best,
Eric

**Comment by adehgha** [comment]
Eric,

Unfortunately I can't see the attachments. BTW I wonder if you are using a 32bit OS. Please let me know if that is the case.

I am working on some changes in the package that would eliminate the need for the user to worry about the data type and the OS dependency.

Regarding your question about converting the input to `int64` inside the `lcm_array` and `gcd_array` functions; these functions should only operate on integers and since they are called from different parts of the package it is necessary to check if the input is in fact integer and not double. I am actually going to use your suggestion inside these functions (allow any type of integer) and will satisfy the `int64` criterion in the upstream. This should be already taken care of on a 64bit OS.

I will soon put together a tutorial on how to use GBpy to run a Grain Boundary (GB) simulation. In the meantime [our recent publication](http://www.sciencedirect.com/science/article/pii/S0927025615006436) with the title **_A simple faceting model for the interfacial and cleavage energies of Σ3 grain boundaries in the complete boundary plane orientation space_** explains in detail how we set up the simulation box to find the structure of the GBs with minimum energy. If you look at the [supplementary information](http://www.sciencedirect.com/science/article/pii/S0927025615006436#appd002) of this article you will find sample LAMMPS input files that will perform the above GB simulation. The basis vectors of the simulation box and the DSC lattice basis vectors are directly extracted from the GBpy. Please let me know if you have any questions.

**Comment by adehgha** [comment]
I pushed the changes and it should work now. Let me know if the latest changes does not resolve your problem.
